# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-skype}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ted Han"]
  s.date = %q{2011-04-12}
  s.description = %q{DataMapper models wrapping Skype v5's sqlite tables}
  s.email = %q{gems@knowtheory.net}
  s.files = [
    "Readme.markdown",
    "VERSION",
    "lib/dm-skype.rb",
    "lib/dm-skype/models.rb",
    "lib/dm-skype/models/account.rb",
    "lib/dm-skype/models/alert.rb",
    "lib/dm-skype/models/call.rb",
    "lib/dm-skype/models/call_member.rb",
    "lib/dm-skype/models/chat.rb",
    "lib/dm-skype/models/chat_member.rb",
    "lib/dm-skype/models/contact.rb",
    "lib/dm-skype/models/contact_group.rb",
    "lib/dm-skype/models/conversation.rb",
    "lib/dm-skype/models/message.rb",
    "lib/dm-skype/models/participant.rb",
    "lib/dm-skype/models/sms.rb",
    "lib/dm-skype/models/transfer.rb",
    "lib/dm-skype/models/video.rb",
    "lib/dm-skype/models/voicemail.rb"
  ]
  s.homepage = %q{http://github.com/knowtheory/dm-skype}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{DataMapper models for Skype v5}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.1"])
      s.add_development_dependency(%q<yard>, ["~> 0.6"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 1.3.1"])
      s.add_dependency(%q<yard>, ["~> 0.6"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 1.3.1"])
    s.add_dependency(%q<yard>, ["~> 0.6"])
  end
end

