module Skype
  class Account # CREATE TABLE Accounts (
    include DataMapper::Resource

    property :id,                         Serial  # id, Serial
    property :is_permanent,               Integer # is_permanent, Integer
    property :status,                     Integer # status, Integer
    property :pwdchangestatus,            Integer # pwdchangestatus, Integer
    property :logoutreason,               Integer # logoutreason, Integer
    property :commitstatus,               Integer # commitstatus, Integer
    property :suggested_skypename,        Text    # suggested_skypename, Text
    property :skypeout_balance_currency,  Text    # skypeout_balance_currency, Text
    property :skypeout_balance,           Integer # skypeout_balance, Integer
    property :skypeout_precision,         Integer # skypeout_precision, Integer
    property :skypein_numbers,            Text    # skypein_numbers, Text
    property :subscriptions,              Text    # subscriptions, Text
    property :cblsyncstatus,              Integer # cblsyncstatus, Integer
    property :offline_callforward,        Text    # offline_callforward, Text
    property :chat_policy,                Integer # chat_policy, Integer
    property :skype_call_policy,          Integer # skype_call_policy, Integer
    property :pstn_call_policy,           Integer # pstn_call_policy, Integer
    property :avatar_policy,              Integer # avatar_policy, Integer
    property :buddycount_policy,          Integer # buddycount_policy, Integer
    property :timezone_policy,            Integer # timezone_policy, Integer
    property :webpresence_policy,         Integer # webpresence_policy, Integer
    property :phonenumbers_policy,        Integer # phonenumbers_policy, Integer
    property :voicemail_policy,           Integer # voicemail_policy, Integer
    property :authrequest_policy,         Integer # authrequest_policy, Integer
    property :ad_policy,                  Integer # ad_policy, Integer
    property :partner_optedout,           Text    # partner_optedout, Text
    property :service_provider_info,      Text    # service_provider_info, Text
    property :registration_timestamp,     Integer # registration_timestamp, Integer
    property :nr_of_other_instances,      Integer # nr_of_other_instances, Integer
    property :owner_under_legal_age,      Integer # owner_under_legal_age, Integer
    property :type,                       Integer # type, Integer
    property :skypename,                  Text    # skypename, Text
    property :pstnnumber,                 Text    # pstnnumber, Text
    property :fullname,                   Text    # fullname, Text
    property :birthday,                   Integer # birthday, Integer
    property :gender,                     Integer # gender, Integer
    property :languages,                  Text    # languages, Text
    property :country,                    Text    # country, Text
    property :province,                   Text    # province, Text
    property :city,                       Text    # city, Text
    property :phone_home,                 Text    # phone_home, Text
    property :phone_office,               Text    # phone_office, Text
    property :phone_mobile,               Text    # phone_mobile, Text
    property :emails,                     Text    # emails, Text
    property :homepage,                   Text    # homepage, Text
    property :about,                      Text    # about, Text
    property :profile_timestamp,          Integer # profile_timestamp, Integer
    property :received_authrequest,       Text    # received_authrequest, Text
    property :displayname,                Text    # displayname, Text
    property :refreshing,                 Integer # refreshing, Integer
    property :given_authlevel,            Integer # given_authlevel, Integer
    property :aliases,                    Text    # aliases, Text
    property :authreq_timestamp,          Integer # authreq_timestamp, Integer
    property :mood_text,                  Text    # mood_text, Text
    property :timezone,                   Integer # timezone, Integer
    property :nrof_authed_buddies,        Integer # nrof_authed_buddies, Integer
    property :ipcountry,                  Text    # ipcountry, Text
    property :given_displayname,          Text    # given_displayname, Text
    property :availability,               Integer # availability, Integer
    property :lastonline_timestamp,       Integer # lastonline_timestamp, Integer
    #property :capabilities BLOB,                 #     capabilities BLOB,
    #property :avatar_image BLOB,                 #     avatar_image BLOB,
    property :assigned_speeddial,         Text    # assigned_speeddial, Text
    property :lastused_timestamp,         Integer # lastused_timestamp, Integer
    property :authrequest_count,          Integer # authrequest_count, Integer
    property :assigned_comment,           Text    # assigned_comment, Text
    property :alertstring,                Text    # alertstring, Text
    property :avatar_timestamp,           Integer # avatar_timestamp, Integer
    property :mood_timestamp,             Integer # mood_timestamp, Integer
    property :rich_mood_text,             Text    # rich_mood_text, Text
    #property :synced_email BLOB,                 #     synced_email BLOB,
    property :set_availability,           Integer # set_availability, Integer
    #property :options_change_future BLOB,        #     options_change_future BLOB,
    property :authorized_time,            Integer # authorized_time, Integer
    property :sent_authrequest,           Text    # sent_authrequest, Text
    property :sent_authrequest_time,      Integer # sent_authrequest_time, Integer
    property :sent_authrequest_serial,    Integer #     sent_authrequest_serial, Integer
    #property :buddyblob BLOB,                    #     buddyblob BLOB,
    #property :cbl_future BLOB,                   #     cbl_future BLOB,
    property :node_capabilities,          Integer # node_capabilities, Integer
    property :node_capabilities_and,      Integer # node_capabilities_and, Integer
    property :revoked_auth,               Integer # revoked_auth, Integer
    property :added_in_shared_group,      Integer # added_in_shared_group, Integer
    property :in_shared_group,            Integer # in_shared_group, Integer
    #property :authreq_history BLOB,              #     authreq_history BLOB,
    #property :profile_attachments BLOB,          #     profile_attachments BLOB,
    property :stack_version,              Integer # stack_version, Integer
    property :offline_authreq_id,         Integer # offline_authreq_id, Integer
    #property :verified_email BLOB,               #     verified_email BLOB,
    #property :verified_company BLOB,             #     verified_company BLOB,
    #property :cbl_profile_blob BLOB);            #     cbl_profile_blob BLOB);

    # CREATE INDEX IX_Accounts_skypename ON Accounts (skypename);
  end
end